// 路亚钓鱼网站 - 完整数据库
// 包含 30 个钓点 + 20 款装备

// ============ 钓点数据库（30 个） ============
const spotsDatabase = [
    // 浙江省（5 个）
    {
        id: 1,
        name: '千岛湖中心湖区',
        province: '浙江',
        city: '杭州',
        fish: ['鲈鱼', '鳜鱼', '翘嘴', '红眼'],
        type: 'paid',
        price: '150 元/天',
        rating: 4.8,
        reviews: 1256,
        image: 'from-blue-400 to-blue-600',
        description: '国内顶级路亚圣地，水质清澈，鱼种丰富，四季可钓',
        tags: ['热门', '推荐'],
        coords: { lat: 29.6067, lng: 119.0319 },
        bestSeason: '春秋',
        difficulty: '中级'
    },
    {
        id: 2,
        name: '千岛湖东南湖区',
        province: '浙江',
        city: '杭州',
        fish: ['鲈鱼', '翘嘴', '鲌鱼'],
        type: 'paid',
        price: '120 元/天',
        rating: 4.6,
        reviews: 834,
        image: 'from-blue-300 to-blue-500',
        description: '相比中心湖区人少，鱼情不错，适合安静作钓',
        tags: ['人少'],
        coords: { lat: 29.5234, lng: 119.1234 },
        bestSeason: '春秋',
        difficulty: '初级'
    },
    {
        id: 3,
        name: '新安江水库',
        province: '浙江',
        city: '建德',
        fish: ['鳡鱼', '翘嘴', '鲈鱼'],
        type: 'free',
        price: '免费',
        rating: 4.7,
        reviews: 567,
        image: 'from-cyan-400 to-cyan-600',
        description: '巨物出没地，鳡鱼爱好者的天堂',
        tags: ['免费', '巨物'],
        coords: { lat: 29.4567, lng: 119.2345 },
        bestSeason: '夏季',
        difficulty: '高级'
    },
    {
        id: 4,
        name: '富春江桐庐段',
        province: '浙江',
        city: '桐庐',
        fish: ['翘嘴', '鲌鱼', '黑鱼'],
        type: 'free',
        price: '免费',
        rating: 4.5,
        reviews: 423,
        image: 'from-green-400 to-green-600',
        description: '江钓好去处，水流较急，适合有一定经验的钓友',
        tags: ['免费', '江钓'],
        coords: { lat: 29.7890, lng: 119.6789 },
        bestSeason: '春秋',
        difficulty: '中级'
    },
    {
        id: 5,
        name: '东钱湖',
        province: '浙江',
        city: '宁波',
        fish: ['鲈鱼', '翘嘴', '鲫鱼'],
        type: 'paid',
        price: '80 元/天',
        rating: 4.4,
        reviews: 356,
        image: 'from-teal-400 to-teal-600',
        description: '宁波周边最近的路亚钓点，交通便利',
        tags: ['近郊'],
        coords: { lat: 29.7654, lng: 121.6543 },
        bestSeason: '四季',
        difficulty: '初级'
    },
    
    // 广东省（5 个）
    {
        id: 6,
        name: '万绿湖主湖区',
        province: '广东',
        city: '河源',
        fish: ['鲈鱼', '红眼', '草鱼', '翘嘴'],
        type: 'paid',
        price: '100 元/天',
        rating: 4.7,
        reviews: 892,
        image: 'from-green-400 to-green-600',
        description: '华南地区知名路亚钓场，鲈鱼密度高，适合新手',
        tags: ['推荐', '新手友好'],
        coords: { lat: 23.7654, lng: 114.6789 },
        bestSeason: '秋冬',
        difficulty: '初级'
    },
    {
        id: 7,
        name: '新丰江水库',
        province: '广东',
        city: '河源',
        fish: ['鲈鱼', '鳜鱼', '翘嘴'],
        type: 'paid',
        price: '120 元/天',
        rating: 4.6,
        reviews: 645,
        image: 'from-emerald-400 to-emerald-600',
        description: '水深鱼大，适合有一定经验的钓友',
        tags: ['大鱼'],
        coords: { lat: 23.8901, lng: 114.5678 },
        bestSeason: '秋冬',
        difficulty: '中级'
    },
    {
        id: 8,
        name: '流溪河水库',
        province: '广东',
        city: '广州',
        fish: ['鲈鱼', '翘嘴', '黑鱼'],
        type: 'paid',
        price: '150 元/天',
        rating: 4.5,
        reviews: 534,
        image: 'from-lime-400 to-lime-600',
        description: '广州周边最近的大型路亚钓场',
        tags: ['近郊'],
        coords: { lat: 23.5678, lng: 113.7890 },
        bestSeason: '春秋',
        difficulty: '初级'
    },
    {
        id: 9,
        name: '高州水库',
        province: '广东',
        city: '茂名',
        fish: ['鲈鱼', '红眼', '翘嘴'],
        type: 'free',
        price: '免费',
        rating: 4.6,
        reviews: 423,
        image: 'from-green-300 to-green-500',
        description: '粤西地区知名钓点，免费开放',
        tags: ['免费'],
        coords: { lat: 21.9876, lng: 110.8765 },
        bestSeason: '秋冬',
        difficulty: '中级'
    },
    {
        id: 10,
        name: '枫树坝水库',
        province: '广东',
        city: '惠州',
        fish: ['鲈鱼', '鳜鱼', '翘嘴'],
        type: 'paid',
        price: '100 元/天',
        rating: 4.4,
        reviews: 367,
        image: 'from-teal-300 to-teal-500',
        description: '惠州周边好去处，鱼情稳定',
        tags: [],
        coords: { lat: 23.2345, lng: 114.9876 },
        bestSeason: '春秋',
        difficulty: '初级'
    },
    
    // 湖北省（4 个）
    {
        id: 11,
        name: '丹江口水库',
        province: '湖北',
        city: '十堰',
        fish: ['鳡鱼', '翘嘴', '鲌鱼', '红眼'],
        type: 'free',
        price: '免费',
        rating: 4.9,
        reviews: 634,
        image: 'from-purple-400 to-purple-600',
        description: '北方最大淡水湖，巨物频出，鳡鱼天堂',
        tags: ['新晋', '免费', '巨物'],
        coords: { lat: 32.5678, lng: 111.2345 },
        bestSeason: '春秋',
        difficulty: '高级'
    },
    {
        id: 12,
        name: '三峡水库',
        province: '湖北',
        city: '宜昌',
        fish: ['鳡鱼', '鲈鱼', '翘嘴'],
        type: 'free',
        price: '免费',
        rating: 4.8,
        reviews: 523,
        image: 'from-indigo-400 to-indigo-600',
        description: '世界级水利工程，鱼种丰富，景色壮观',
        tags: ['免费', '特色'],
        coords: { lat: 30.8765, lng: 111.0987 },
        bestSeason: '春秋',
        difficulty: '高级'
    },
    {
        id: 13,
        name: '梁子湖',
        province: '湖北',
        city: '鄂州',
        fish: ['鳜鱼', '鲈鱼', '翘嘴'],
        type: 'paid',
        price: '80 元/天',
        rating: 4.5,
        reviews: 412,
        image: 'from-blue-300 to-blue-500',
        description: '湖北第二大淡水湖，鳜鱼资源丰富',
        tags: ['鳜鱼'],
        coords: { lat: 30.3456, lng: 114.6789 },
        bestSeason: '春秋',
        difficulty: '中级'
    },
    {
        id: 14,
        name: '洪湖',
        province: '湖北',
        city: '荆州',
        fish: ['黑鱼', '鲈鱼', '翘嘴'],
        type: 'paid',
        price: '60 元/天',
        rating: 4.3,
        reviews: 345,
        image: 'from-green-300 to-green-500',
        description: '革命老区，水草丰富，黑鱼较多',
        tags: ['黑鱼'],
        coords: { lat: 29.8765, lng: 113.4567 },
        bestSeason: '夏季',
        difficulty: '初级'
    },
    
    // 江苏省（4 个）
    {
        id: 15,
        name: '太湖西山岛',
        province: '江苏',
        city: '苏州',
        fish: ['翘嘴', '鲌鱼', '黑鱼'],
        type: 'free',
        price: '免费',
        rating: 4.5,
        reviews: 523,
        image: 'from-cyan-400 to-cyan-600',
        description: '长三角经典钓点，交通便利，适合周末短途',
        tags: ['免费', '近郊'],
        coords: { lat: 31.0987, lng: 120.2345 },
        bestSeason: '春秋',
        difficulty: '初级'
    },
    {
        id: 16,
        name: '长江口崇明岛',
        province: '江苏',
        city: '南通',
        fish: ['海鲈', '鲻鱼', '鳗鱼'],
        type: 'free',
        price: '免费',
        rating: 4.4,
        reviews: 289,
        image: 'from-teal-400 to-teal-600',
        description: '咸淡水交汇处，海钓体验，季节性强',
        tags: ['免费', '海钓'],
        coords: { lat: 31.6789, lng: 121.5678 },
        bestSeason: '春秋',
        difficulty: '中级'
    },
    {
        id: 17,
        name: '天目湖',
        province: '江苏',
        city: '常州',
        fish: ['鲈鱼', '翘嘴', '鳜鱼'],
        type: 'paid',
        price: '120 元/天',
        rating: 4.6,
        reviews: 456,
        image: 'from-blue-400 to-blue-600',
        description: '旅游胜地，水质优良，鱼质鲜美',
        tags: ['推荐'],
        coords: { lat: 31.3456, lng: 119.4567 },
        bestSeason: '春秋',
        difficulty: '中级'
    },
    {
        id: 18,
        name: '骆马湖',
        province: '江苏',
        city: '宿迁',
        fish: ['翘嘴', '鲌鱼', '鳜鱼'],
        type: 'free',
        price: '免费',
        rating: 4.4,
        reviews: 334,
        image: 'from-sky-400 to-sky-600',
        description: '苏北地区大型淡水湖，鱼情不错',
        tags: ['免费'],
        coords: { lat: 34.0987, lng: 118.2345 },
        bestSeason: '春秋',
        difficulty: '初级'
    },
    
    // 云南省（3 个）
    {
        id: 19,
        name: '泸沽湖',
        province: '云南',
        city: '丽江',
        fish: ['裂腹鱼', '细鳞鱼'],
        type: 'paid',
        price: '200 元/天',
        rating: 4.9,
        reviews: 412,
        image: 'from-indigo-400 to-indigo-600',
        description: '高原湖泊，风景绝美，特有鱼种，路亚 + 旅行',
        tags: ['特色', '高原'],
        coords: { lat: 27.6789, lng: 100.8765 },
        bestSeason: '春夏',
        difficulty: '中级'
    },
    {
        id: 20,
        name: '抚仙湖',
        province: '云南',
        city: '玉溪',
        fish: ['抗浪鱼', '鲤鱼'],
        type: 'paid',
        price: '180 元/天',
        rating: 4.8,
        reviews: 256,
        image: 'from-sky-400 to-sky-600',
        description: '中国第二深水湖，水质极佳，高原风光',
        tags: ['特色', '深水'],
        coords: { lat: 24.5678, lng: 102.8765 },
        bestSeason: '春夏',
        difficulty: '高级'
    },
    {
        id: 21,
        name: '洱海',
        province: '云南',
        city: '大理',
        fish: ['鲫鱼', '鲤鱼'],
        type: 'paid',
        price: '150 元/天',
        rating: 4.7,
        reviews: 345,
        image: 'from-blue-300 to-blue-500',
        description: '苍山洱海，风景如画，休闲路亚',
        tags: ['特色', '休闲'],
        coords: { lat: 25.8765, lng: 100.1234 },
        bestSeason: '春秋',
        difficulty: '初级'
    },
    
    // 四川省（3 个）
    {
        id: 22,
        name: '升钟湖',
        province: '四川',
        city: '南充',
        fish: ['鲈鱼', '翘嘴', '鳜鱼'],
        type: 'paid',
        price: '120 元/天',
        rating: 4.6,
        reviews: 378,
        image: 'from-emerald-400 to-emerald-600',
        description: '西南地区最大人工湖，鱼种多样，配套设施完善',
        tags: ['推荐'],
        coords: { lat: 31.2345, lng: 106.0987 },
        bestSeason: '春秋',
        difficulty: '中级'
    },
    {
        id: 23,
        name: '黑龙滩水库',
        province: '四川',
        city: '眉山',
        fish: ['鲈鱼', '翘嘴', '红眼'],
        type: 'paid',
        price: '100 元/天',
        rating: 4.5,
        reviews: 289,
        image: 'from-green-400 to-green-600',
        description: '成都周边热门钓点，周末人气旺',
        tags: ['近郊'],
        coords: { lat: 30.0987, lng: 104.1234 },
        bestSeason: '春秋',
        difficulty: '初级'
    },
    {
        id: 24,
        name: '三岔湖',
        province: '四川',
        city: '成都',
        fish: ['鲈鱼', '翘嘴', '黑鱼'],
        type: 'paid',
        price: '80 元/天',
        rating: 4.4,
        reviews: 423,
        image: 'from-teal-400 to-teal-600',
        description: '成都东郊最近的大型钓点',
        tags: ['近郊'],
        coords: { lat: 30.3456, lng: 104.2345 },
        bestSeason: '四季',
        difficulty: '初级'
    },
    
    // 北京市（1 个）
    {
        id: 25,
        name: '怀柔水库',
        province: '北京',
        city: '北京',
        fish: ['翘嘴', '鲌鱼', '黑鱼'],
        type: 'free',
        price: '免费',
        rating: 4.3,
        reviews: 445,
        image: 'from-gray-400 to-gray-600',
        description: '北京周边最近的大型路亚钓点，适合京津冀钓友',
        tags: ['免费', '近郊'],
        coords: { lat: 40.3456, lng: 116.5678 },
        bestSeason: '春秋',
        difficulty: '初级'
    },
    
    // 其他省份（5 个）
    {
        id: 26,
        name: '陆浑水库',
        province: '河南',
        city: '洛阳',
        fish: ['鳜鱼', '鲈鱼', '翘嘴'],
        type: 'free',
        price: '免费',
        rating: 4.5,
        reviews: 234,
        image: 'from-blue-300 to-blue-500',
        description: '中原地区优质钓点，鳜鱼资源丰富',
        tags: ['免费', '鳜鱼'],
        coords: { lat: 34.2345, lng: 112.3456 },
        bestSeason: '春秋',
        difficulty: '中级'
    },
    {
        id: 27,
        name: '岗南水库',
        province: '河北',
        city: '石家庄',
        fish: ['翘嘴', '鲌鱼', '黑鱼'],
        type: 'paid',
        price: '60 元/天',
        rating: 4.3,
        reviews: 198,
        image: 'from-sky-300 to-sky-500',
        description: '河北地区知名钓点，交通便利',
        tags: [],
        coords: { lat: 38.2345, lng: 114.1234 },
        bestSeason: '春秋',
        difficulty: '初级'
    },
    {
        id: 28,
        name: '大伙房水库',
        province: '辽宁',
        city: '抚顺',
        fish: ['鳡鱼', '翘嘴', '鲈鱼'],
        type: 'paid',
        price: '100 元/天',
        rating: 4.6,
        reviews: 267,
        image: 'from-indigo-300 to-indigo-500',
        description: '东北地区大型水库，巨物出没',
        tags: ['巨物'],
        coords: { lat: 41.8765, lng: 124.0987 },
        bestSeason: '夏季',
        difficulty: '高级'
    },
    {
        id: 29,
        name: '松花湖',
        province: '吉林',
        city: '吉林',
        fish: ['鳡鱼', '翘嘴', '鲈鱼'],
        type: 'paid',
        price: '120 元/天',
        rating: 4.7,
        reviews: 312,
        image: 'from-blue-400 to-blue-600',
        description: '东北著名钓场，冬季冰钓也很有名',
        tags: ['特色'],
        coords: { lat: 43.5678, lng: 126.8765 },
        bestSeason: '夏冬',
        difficulty: '中级'
    },
    {
        id: 30,
        name: '百花湖',
        province: '贵州',
        city: '贵阳',
        fish: ['鲈鱼', '翘嘴', '鳜鱼'],
        type: 'paid',
        price: '80 元/天',
        rating: 4.5,
        reviews: 189,
        image: 'from-emerald-300 to-emerald-500',
        description: '贵州高原湖泊，水质清澈，景色优美',
        tags: ['高原'],
        coords: { lat: 26.6789, lng: 106.5678 },
        bestSeason: '春夏',
        difficulty: '初级'
    }
];

// ============ 装备数据库（20 款） ============
const gearDatabase = [
    // 鱼竿（6 款）
    {
        id: 1,
        name: 'Shimano 禧玛诺 EXP',
        category: 'rod',
        price: 1299,
        rating: 4.8,
        reviews: 356,
        image: 'from-gray-300 to-gray-400',
        specs: { '长度': '1.98m', '调性': 'ML', '重量': '95g', '饵重': '3-14g' },
        scores: { 灵敏度：95, 耐用性：90, 性价比：75, 外观：92 },
        pros: ['超高灵敏度', '轻量化设计', '导环质量优秀'],
        cons: ['价格偏高', '新手不易上手']
    },
    {
        id: 2,
        name: '海伯 战神系列',
        category: 'rod',
        price: 358,
        rating: 4.5,
        reviews: 289,
        image: 'from-red-300 to-red-400',
        specs: { '长度': '2.13m', '调性': 'M', '重量': '125g', '饵重': '7-28g' },
        scores: { 灵敏度：80, 耐用性：92, 性价比：95, 外观：85 },
        pros: ['性价比极高', '皮实耐用', '适合新手'],
        cons: ['灵敏度一般', '重量偏大']
    },
    {
        id: 3,
        name: 'Daiwa 达亿瓦 TATULA 竿',
        category: 'rod',
        price: 899,
        rating: 4.7,
        reviews: 234,
        image: 'from-blue-300 to-blue-400',
        specs: { '长度': '2.03m', '调性': 'M', '重量': '105g', '饵重': '5-20g' },
        scores: { 灵敏度：88, 耐用性：90, 性价比：85, 外观：90 },
        pros: ['平衡性好', '品牌可靠', '手感舒适'],
        cons: ['价格中等', '配件贵']
    },
    {
        id: 4,
        name: '光威 赤刃',
        category: 'rod',
        price: 199,
        rating: 4.3,
        reviews: 567,
        image: 'from-orange-300 to-orange-400',
        specs: { '长度': '1.80m', '调性': 'ML', '重量': '110g', '饵重': '3-12g' },
        scores: { 灵敏度：75, 耐用性：88, 性价比：98, 外观：80 },
        pros: ['超低价', '国产良心', '新手首选'],
        cons: ['做工一般', '灵敏度低']
    },
    {
        id: 5,
        name: 'Megabass Great Hunting',
        category: 'rod',
        price: 2599,
        rating: 4.9,
        reviews: 123,
        image: 'from-purple-300 to-purple-400',
        specs: { '长度': '1.93m', '调性': 'M', '重量': '88g', '饵重': '5-18g' },
        scores: { 灵敏度：98, 耐用性：92, 性价比：65, 外观：96 },
        pros: ['顶级工艺', '极致性能', '收藏价值'],
        cons: ['价格昂贵', '需要技术']
    },
    {
        id: 6,
        name: '钓之屋 潜猎者',
        category: 'rod',
        price: 459,
        rating: 4.6,
        reviews: 345,
        image: 'from-green-300 to-green-400',
        specs: { '长度': '2.10m', '调性': 'ML', '重量': '100g', '饵重': '4-16g' },
        scores: { 灵敏度：85, 耐用性：90, 性价比：90, 外观：88 },
        pros: ['国产品牌', '性价比高', '性能均衡'],
        cons: ['品牌知名度低', '二手难出']
    },
    
    // 鱼轮（6 款）
    {
        id: 7,
        name: 'Daiwa 达亿瓦 TATULA',
        category: 'reel',
        price: 899,
        rating: 4.7,
        reviews: 423,
        image: 'from-blue-300 to-blue-400',
        specs: { '类型': '水滴轮', '速比': '6.3:1', '重量': '205g', '线容量': '0.35mm-100m' },
        scores: { 抛投性：92, 耐用性：88, 性价比：85, 刹车系统：90 },
        pros: ['T 翼系统防炸线', '性价比高', '适合新手'],
        cons: ['满载时略重', '噪音稍大']
    },
    {
        id: 8,
        name: 'Abu Garcia REVO',
        category: 'reel',
        price: 1599,
        rating: 4.8,
        reviews: 234,
        image: 'from-purple-300 to-purple-400',
        specs: { '类型': '水滴轮', '速比': '7.3:1', '重量': '184g', '轴承': '10+1' },
        scores: { 抛投性：94, 耐用性：93, 性价比：72, 刹车系统：96 },
        pros: ['磁力刹车精准', '高速比', '做工精细'],
        cons: ['价格高', '维护成本高']
    },
    {
        id: 9,
        name: 'Shimano 禧玛诺 SLX',
        category: 'reel',
        price: 799,
        rating: 4.6,
        reviews: 312,
        image: 'from-gray-300 to-gray-400',
        specs: { '类型': '水滴轮', '速比': '6.3:1', '重量': '215g', '轴承': '7+1' },
        scores: { 抛投性：90, 耐用性：90, 性价比：88, 刹车系统：88 },
        pros: ['品牌可靠', '性能稳定', '售后好'],
        cons: ['重量偏大', '外观普通']
    },
    {
        id: 10,
        name: '海伯 阿瑞斯',
        category: 'reel',
        price: 358,
        rating: 4.4,
        reviews: 456,
        image: 'from-red-300 to-red-400',
        specs: { '类型': '水滴轮', '速比': '6.3:1', '重量': '220g', '轴承': '8+1' },
        scores: { 抛投性：85, 耐用性：88, 性价比：95, 刹车系统：82 },
        pros: ['超低价', '国产之光', '新手友好'],
        cons: ['细节粗糙', '噪音大']
    },
    {
        id: 11,
        name: 'Shimano 纺车轮 NASCI',
        category: 'reel',
        price: 699,
        rating: 4.7,
        reviews: 289,
        image: 'from-silver-300 to-silver-400',
        specs: { '类型': '纺车轮', '速比': '5.2:1', '重量': '240g', '轴承': '5+1' },
        scores: { 抛投性：88, 耐用性：92, 性价比：85, 顺滑度：94 },
        pros: ['超级顺滑', '耐用', '适合远投'],
        cons: ['速比低', '不适合精细操作']
    },
    {
        id: 12,
        name: 'Daiwa 纺车轮 FREAMS',
        category: 'reel',
        price: 459,
        rating: 4.5,
        reviews: 367,
        image: 'from-blue-200 to-blue-300',
        specs: { '类型': '纺车轮', '速比': '5.3:1', '重量': '235g', '轴承': '4+1' },
        scores: { 抛投性：86, 耐用性：90, 性价比：90, 顺滑度：88 },
        pros: ['性价比高', '轻便', '适合新手'],
        cons: ['轴承少', '长期耐用性一般']
    },
    
    // 假饵（5 款）
    {
        id: 13,
        name: 'Megabass VISION 110',
        category: 'lure',
        price: 168,
        rating: 4.9,
        reviews: 567,
        image: 'from-green-300 to-green-400',
        specs: { '类型': '米诺', '长度': '110mm', '重量': '14g', '潜深': '0.8-1.2m' },
        scores: { 泳姿：98, 耐用性：85, 性价比：70, 诱鱼效果：96 },
        pros: ['经典泳姿', '鲈鱼杀手', '品质稳定'],
        cons: ['价格偏高', '容易挂底']
    },
    {
        id: 14,
        name: 'DUO Tide Minnow',
        category: 'lure',
        price: 145,
        rating: 4.8,
        reviews: 423,
        image: 'from-blue-300 to-blue-400',
        specs: { '类型': '米诺', '长度': '105mm', '重量': '13g', '潜深': '1.0-1.5m' },
        scores: { 泳姿：96, 耐用性：88, 性价比：75, 诱鱼效果：94 },
        pros: ['海钓神器', '抛投远', '耐用'],
        cons: ['价格高', '淡水效果一般']
    },
    {
        id: 15,
        name: '亮片套装',
        category: 'lure',
        price: 59,
        rating: 4.5,
        reviews: 789,
        image: 'from-yellow-300 to-yellow-400',
        specs: { '类型': '亮片', '重量': '3.5g-10g', '数量': '10 枚', '颜色': '混色' },
        scores: { 泳姿：85, 耐用性：95, 性价比：98, 诱鱼效果：88 },
        pros: ['万能饵', '超便宜', '新手必备'],
        cons: ['易挂底', '目标鱼有限']
    },
    {
        id: 16,
        name: '软饵套装',
        category: 'lure',
        price: 39,
        rating: 4.4,
        reviews: 634,
        image: 'from-orange-300 to-orange-400',
        specs: { '类型': '软饵', '长度': '5-8cm', '数量': '20 尾', '颜色': '混色' },
        scores: { 泳姿：88, 耐用性：75, 性价比：95, 诱鱼效果：90 },
        pros: ['便宜', '种类多', '底层搜索'],
        cons: ['易损耗', '需要配铅']
    },
    {
        id: 17,
        name: 'VIB 金属振动饵',
        category: 'lure',
        price: 89,
        rating: 4.6,
        reviews: 345,
        image: 'from-silver-300 to-silver-400',
        specs: { '类型': 'VIB', '重量': '10g', '数量': '3 枚', '颜色': '混色' },
        scores: { 泳姿：92, 耐用性：90, 性价比：85, 诱鱼效果：92 },
        pros: ['全水层', '诱鱼强', '远投好'],
        cons: ['易挂底', '操作单一']
    },
    
    // 配件（3 款）
    {
        id: 18,
        name: 'OWNER 钩子套装',
        category: 'accessory',
        price: 89,
        rating: 4.6,
        reviews: 512,
        image: 'from-yellow-300 to-yellow-400',
        specs: { '数量': '50 枚', '型号': '混合装', '材质': '高碳钢', '涂层': '黑色' },
        scores: { 锋利度：94, 耐用性：88, 性价比：92, 防锈性：85 },
        pros: ['超级锋利', '性价比高', '型号齐全'],
        cons: ['容易生锈', '小号偏软']
    },
    {
        id: 19,
        name: 'Sunline 鱼线',
        category: 'accessory',
        price: 68,
        rating: 4.7,
        reviews: 423,
        image: 'from-green-200 to-green-300',
        specs: { '类型': 'PE 线', '号数': '1.5 号', '长度': '150m', '拉力': '16lb' },
        scores: { 强度：92, 耐用性：90, 性价比：88, 顺滑度：90 },
        pros: ['日本品牌', '质量稳定', '抛投顺'],
        cons: ['价格中等', '假货多']
    },
    {
        id: 20,
        name: '路亚钳套装',
        category: 'accessory',
        price: 129,
        rating: 4.5,
        reviews: 234,
        image: 'from-gray-300 to-gray-400',
        specs: { '材质': '不锈钢', '长度': '23cm', '功能': '多功能', '配件': '控鱼器 + 剪刀' },
        scores: { 实用性：95, 耐用性：90, 性价比：85, 便携性：88 },
        pros: ['功能齐全', '不锈钢', '必备工具'],
        cons: ['重量大', '占用空间']
    }
];

// 导出供页面使用
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { spotsDatabase, gearDatabase };
}
